apiVersion: core.cic.io/v1
kind: PodGroup
metadata:
  labels:
    app.kubernetes.io/name: podgroup
    app.kubernetes.io/managed-by: kustomize
  name: podgroup-sample
spec:
  podList:
    - metadata:
        name: p1
        labels:
            app: pg1
      spec:
        containers:
          - name: ngxinx
            image: nginx:latest
            ports:
              - containerPort: 80
    - metadata:
        name: p1
        labels:
            app: pg1
      spec:
        containers:
          - name: ngxinx
            image: nginx:latest
            ports:
              - containerPort: 80
